# netlify.toml
[build]
  publish = "site"

# apply to all static assets (if your site ever fetches from itself via fetch())
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Strict-Transport-Security    = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy       = "default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self' https://api.openai.com; frame-ancestors 'none'; upgrade-insecure-requests"
    Referrer-Policy              = "strict-origin"
    X-Frame-Options              = "DENY"
    Permissions-Policy           = "camera=(), microphone=()"

[[headers]]
  for = "/mailto.json"
  [headers.values]
    Cache-Control = "no-store"

[[redirects]]
  from    = "/api/*"
  to      = "/.netlify/functions/:splat"
  status  = 200